Do not crash with internal error on corrupted sysctl file
yast/yast-network pull request #1242
Opened 2021-07-01 08:57 UTC by mchf

https://bugzilla.suse.com/show_bug.cgi?id=1185936

## Problem ##

When any of sysctl files accessed by yast2-network was corrupted, yast2 lan crashed with internal error

## Solution ##

Implemented augeas exception handling together with using new issues reporting mechanism for error report.

2021-07-01 13:08 UTC, imobachgs requested changes
In general, it looks good (the approach is pretty similar to what do while reading the configuration). I wonder whether we should unify *Result classes.

2021-07-01 13:08 UTC, imobachgs commented on src/modules/Lan.rb
> +        return false unless Y2Issues.report(result.issues) == :yes
Beware that this API changed recently and the report method now returns a boolean. See https://github.com/yast/yast-network/pull/1240/files#diff-c536d97bfa2e800b076011ec2976dae8b9c77b83fec29c7a1741554d1f8750c0.

2021-07-01 17:37 UTC, mchf commented
> In general, it looks good (the approach is pretty similar to what do while reading the configuration). I wonder whether we should unify *Result classes.

to make it similar to the read case was an intention ;-)  I was thinking of unifying result classes as well ... as these classes are very simple ... and in fact the same.

2021-07-02 06:48 UTC, imobachgs approved these changes

2021-07-02 06:50 UTC, merged